---
name: test
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  rspec:
    name: "Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }}"
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
        gemfile:
          - omniauth_2.0
          - omniauth_2.1

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_WITHOUT: development

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
        env:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3

      - run: |
          bundle exec rspec --color --format documentation

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  rubocop:
    name: rubocop
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.6"
          bundler-cache: true
        env:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3

      - run: bundle exec rubocop --parallel --fail-level E
